### ISSUE TITLE
Foundry V11 Update?

### ISSUE THREAD

**Issue by SageSaga25** [Kekilla0/Item-Macro#66]
While Item-Macro seems to run on V11 it causes a maximum call stack error.

```
RangeError: undefined. Maximum call stack size exceeded
[Detected 1 package: itemacro]
    at mergeObject (commons.js:2667:23)
    at _mergeUpdate (commons.js:2737:14)
    at mergeObject (commons.js:2694:41)
    at _mergeUpdate (commons.js:2737:14)
    at mergeObject (commons.js:2694:41)
    at _mergeUpdate (commons.js:2737:14)
    at mergeObject (commons.js:2694:41) (Repeats till it runs out of space)
```
I am pretty clueless when it comes to these things, but I figured I should report it.

**Comment by trioderegion** [comment]
https://github.com/Kekilla0/Item-Macro/releases/download/1.9.0%2B1/module.json
